[package]
name = "otlp_builder"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"
license = "Apache-2.0"

[lib]
crate-type = ["rlib", "cdylib"]

[lints]
workspace = true

[dependencies]
# Use the repo's opentelemetry-proto crate directly
opentelemetry-proto = { version = "0.30", default-features = false, features = ["logs", "gen-tonic-messages"] }
prost = "0.13"
