[package]
name = "geneva-uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry-proto = {workspace = true, default-features = false, features = ["logs", "gen-tonic-messages"]}
base64 = "0.22"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
uuid = { version = "1.0", features = ["v4"] }
# TODO - support both native-tls and rustls
reqwest = { version = "0.12", features = ["native-tls", "native-tls-alpn"]}
native-tls = "0.2" 
thiserror = "2.0"

[features]
self_signed_certs = [] # Empty by default for security
default = ["self_signed_certs"] # TODO - remove this feature before release

[dev-dependencies]
rcgen = "0.13"
openssl = "0.10"
tempfile = "3.5"
wiremock = "0.6"

[lints]
workspace = true