[package]
name = "geneva-uploader"
version = "0.1.0"
edition = "2021"

[workspace]

[workspace.dependencies]

[dependencies]
opentelemetry-proto = {default-features = false, features = ["logs", "gen-tonic-messages"], version = "0.29"}
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
uuid = { version = "1.0", features = ["v4"] }
# TODO - support both native-tls and rustls
reqwest = { version = "0.12", features = ["native-tls", "native-tls-alpn"]}
native-tls = "0.2" 
thiserror = "2.0"
chrono = "0.4"
url = "2.2"
md5 = "0.7.0"
hex = "0.4"
lz4_flex = { version = "0.11", features = ["safe-encode"], default-features = false }

[features]
self_signed_certs = [] # Empty by default for security
default = ["self_signed_certs"] # TODO - remove this feature before release

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
rcgen = "0.13"
openssl = { version = "0.10", features = ["vendored"] }
tempfile = "3.5"
wiremock = "0.6"
futures = "0.3"
num_cpus = "1.16"
lz4_flex = { version = "0.11" }

[build-dependencies]
cc = "1.0"


[workspace.lints.rust]
rust_2024_compatibility = { level = "warn", priority = -1 }
# No need to enable those, because it is either unnecessary or results in ugly syntax
if_let_rescope = "allow"
tail_expr_drop_order = "allow"

[workspace.lints.clippy]
all = { level = "warn", priority = 1 }